#config file for @charlesmike
commanders:
  - amihaiemil
ignored:
  - *.xml
  - *.css
  - *.js
  - */index.html
  - https://www.amihaiemil.com/#
  - https://www.amihaiemil.com/page2/
  - https://www.amihaiemil.com/page3/
  - https://www.amihaiemil.com/page4/
  - https://www.amihaiemil.com/page5/
  - https://www.amihaiemil.com/page6/
driver: chrome
